- .github/workflows/ci.yml
- .gitignore
- app/hello.py
- pyproject.toml
- uv.lock
Adds a basic ci pipeline using GitHub Actions to allows for
> Add basic pipeline

- app/hello.py
- app/main.py
- app/model/HelloWorld.py
- pyproject.toml
- tests/manual.http
- uv.lock
Setup simple fastapi including 2 simple demo routes.
---
Depends on #3
> Initialize fastapi project

- .github/workflows/docker.yml
- README.md
- compose-dev.yaml
- compose.yaml
> Build docker image in ci

- .github/workflows/ci.yml
- .github/workflows/docs.yml
#3 does not include freeze the lockfile
- Freeze lockfile
- Prevent sync during run
See [UV - Locking and Syncing](https://docs.astral.sh/uv/concepts/projects/sync/#locking-and-syncing)
> Freeze lockfile in ci

- docs/conf.py
- docs/example-cross-references.rst
- docs/index.rst
- pyproject.toml
- uv.lock
> docs: Sphinx Cross-references

- pyproject.toml
- uv.lock
> Added openqasm3[parser] as dependency

- app/preprocessing/utils.py
- docs/preprocessing.rst
- tests/preprocessing/test_utils.py
Parse `@leqo.input` and `@leqo.output` commands according to our spec.
> feat: Parse io annotation

- app/processing/utils.py
- tests/processing/test_utils.py
> Fix: index parse handle empty

- app/processing/pre/__init__.py
- app/processing/pre/inlining.py
- tests/processing/pre/test_inlining.py
Inline compile-time-constant unsigned integers and positive signed integers.
> feat: Inline integer `const`s

- app/model/CompileRequest.py
- app/model/StatusBody.py
> docs: Add some documentation to the model modules

- app/processing/merge/connections.py
- tests/processing/merge/test_connections.py
> feat: connect qubits

- app/processing/merge/__init__.py
- app/processing/merge/connections.py
- tests/processing/merge/test_connections.py
- tests/processing/merge/test_init.py
Use the previous implemented connect_qubits to merge programs.
> feat: merge with connect

- app/openqasm3/printer.py
- app/processing/__init__.py
- tests/openqasm3/test_printer.py
- tests/processing/merge/test_init.py
- Prevent emission of semicolons after comments
- Rename `print_program` to `leqo_dumps` to match the naming of other methods
- Move `leqo_dumps` to `app.openqasm3.printer`
> fix: `LeqoPrinter`

- app/processing/__init__.py
- app/processing/graph.py
- app/processing/merge/connections.py
- app/processing/optimize/__init__.py
- app/processing/pre/io_parser.py
- tests/processing/merge/test_connections.py
- tests/processing/pre/test_io_parse.py
- Create structure + fetch data required for optimization
- Allow multiple Connection between two Nodes
> feat: requirements for optimization

- .github/workflows/ci.yml
- .gitignore
- pyproject.toml
- uv.lock
- Gather code coverage
- Generate html report
- Upload both
> chore: Gather code coverage

- app/enricher/__init__.py
- app/model/data_types.py
- app/processing/graph.py
- app/processing/merge/connections.py
- app/processing/pre/io_parser.py
- app/processing/size_casting.py
- app/utils.py
- tests/processing/merge/test_connections.py
- tests/processing/pre/test_io_parse.py
- tests/processing/test_size_casting.py
> refactor: use leqo data model

- app/processing/optimize/__init__.py
- tests/processing/test_optimize.py
Remove the if(bool) in the output to be compatible with qiskit.
> fix: qiskit compatible output

- app/enricher/__init__.py
- app/enricher/literals.py
- app/enricher/measure.py
- app/enricher/utils.py
- app/utils.py
- tests/enricher/test_literals.py
- tests/enricher/test_measure.py
- tests/test_utils.py
Enrich trivial nodes by generating an implementation on the fly
> feat: enricher for trivial nodes

- app/main.py
- app/processing/__init__.py
- app/utils.py
> feat: enrich graph

- app/enricher/__init__.py
- app/enricher/literals.py
- app/enricher/measure.py
- app/enricher/merger.py
- app/enricher/splitter.py
- tests/enricher/test_init.py
- tests/enricher/test_literals.py
- tests/enricher/test_measure.py
- tests/enricher/test_merger.py
- tests/enricher/test_splitter.py
> feat: enricher strategy may return multiple results

- app/processing/merge/__init__.py
We called postprocess twice: once in processor and once in merger. One should be removed
> fix: no duplicate postprocess

- app/enricher/measure.py
- tests/enricher/test_measure.py
- New output that gives access to the measured qubit
- Used to uncompute the qubit later (using if-else)
> feat: qubit output for measure node

- tests/baselines/debug/compile/addition.yml
- tests/baselines/debug/compile/merger_splitter.yml
Followup for #162
We added integration tests in #162 that did not account for the new qubit output introduced in #170.
The pipeline in #162 did not fail, because it completed earlier (without the new tests).
Our branch protection now enforces all branches to be up-to-date before merging to prevent this in the future.
> fix: tests on main

- app/enricher/gates.py
- app/services.py
- tests/baselines/debug/compile/gates-broadcasting.yml
- tests/baselines/debug/compile/gates.yml
- tests/enricher/test_gates.py
Automatically generate implementation for gate nodes (with and without params) using a new enricher strategy.
Implementations were adapted from the [frontend](https://github.com/LEQO-Framework/low-code-modeler/blob/55896e6e69062d406298850b6c83b9c3018ba874/src/constants/index.tsx#L34-L43).
Enriching gates in the backend enables the use of broadcasting as the backend has full knowledge of the size of all connections.
> feat(enricher): enrich gates

- app/model/CompileRequest.py
- app/processing/__init__.py
- app/processing/converted_graph.py
Extract the model to model transformation into a new `ConvertedProgramGraph`.
This will be the common base for if-else and repeat implementation.
> refactor: model to model transformation

- app/processing/__init__.py
- app/processing/converted_graph.py
- app/processing/graph.py
- app/services.py
- tests/baselines/debug/compile/addition.yml
- tests/baselines/debug/compile/gates-broadcasting.yml
- tests/baselines/debug/compile/gates.yml
- tests/baselines/debug/compile/literals.yml
- tests/baselines/debug/compile/malicious_node_id.yml
- tests/baselines/debug/compile/merger_splitter.yml
- tests/baselines/debug/compile/size_cast.yml
- tests/baselines/test_main.py
Use `uuid5` instead of `uuid4` to get deterministic output
> fix: deterministic output

- app/enricher/gates.py
- app/model/CompileRequest.py
- app/openqasm3/__init__.py
- app/openqasm3/stdgates.py
Added enrichment support for all gates of the openqasm [stdlibrary](https://openqasm.com/language/standard_library.html#api-documentation).
> [!WARNING]
> Gates with more than 1 parameter are still missing
> feat: enrich additional gates

- app/enricher/__init__.py
- app/enricher/db_enricher.py
- app/enricher/encode_value.py
- app/enricher/exceptions.py
- app/enricher/gates.py
- app/enricher/measure.py
- app/enricher/merger.py
- app/enricher/operator.py
- app/enricher/prepare_state.py
- app/enricher/splitter.py
- app/model/exceptions.py
- tests/enricher/test_encode_value.py
- tests/enricher/test_gates.py
- tests/enricher/test_init.py
- tests/enricher/test_measure.py
- tests/enricher/test_merger.py
- tests/enricher/test_operator.py
- tests/enricher/test_prepare_state.py
- tests/enricher/test_splitter.py
Add specialized exception types that communicate client errors during enrichment.
> refactor: better enricher exceptions
